db:
  image: postgres
  expose:
    - "5432"
web:
  build: .
  command: /bin/sh -c "rm -f /fuel_economy/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/fuel_economy
  ports:
    - "3000:3000"
  links:
    - db
